name: tfann
description: Tiny Fast Artificial Neural Network Library (Based on SIMD computations)
version: 0.8.0
repository: https://github.com/gnudles/tfann_dart

environment:
  sdk: "^3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.3
