name: tfann
description: Tiny Fast Artificial Neural Network Library (Based on SIMD computations)
version: 0.6.3+91
repository: https://github.com/gnudles/tfann_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


